### PR TITLE
Tender-Lovin' Care

### PR DESCRIPTION
**Pull request by eightypop**
This updates the dev deps and the webpack config and eslint.

Also outputs the unminified transpiled file for easier debugging and make that the main.

### CODE REVIEW

**Comment by jdlehman** [comment]
👍

**Comment by metaskills** [comment]
screen shot 2017-01-25 at 3 59 27 pm

Meta 👍

**Comment by AEgan** [comment]
screen shot 2017-01-25 at 4 12 23 pm

must go deeper 👍

**Comment by wingrunr21** [comment]
👎  no rollup or webpack v2. Please redo

**Pull request merged**
